version: "3.8"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      - GOOSE_MIGRATION_DIR=migrations
    depends_on:
      - db
    command: >
      sh -c "goose up && /app/nit"

  adminer:
    image: dockette/adminer:pgsql
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  pgdata:
